name: Saver Hunter Crawler

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # 修正這裡：確保讀取了你的 requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Crawler
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          RUN_TYPE: CRAWLER
        run: python app.py
