name: Saver Hunter Crawler

on:
  schedule:
    - cron: '*/30 * * * *' 
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Crawler
        env:
          RUN_TYPE: "CRAWLER"
          MONGODB_URI: ${{ secrets.MONGODB_URI }} # 必須加入這行，讓爬蟲連上雲端庫
          GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }} # 加入這行，讓爬蟲能發信
        run: |
          python app.py
